name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # به‌جای gradlew از Gradle اکشن استفاده می‌کنیم
      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: Build APKs (debug + تلاش برای release)
        run: |
          gradle assembleDebug --no-daemon
          gradle assembleRelease --no-daemon || true

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: myoxford24-apks
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
